import { cn } from '@/lib/utils'
import '@/styles/globals.css'

import { Inter } from 'next/font/google'

const inter = Inter({
	subsets: ['latin'],
	variable: '--font-sans'
})

export const metadata = {
	title: 'Acortador de URL',
	description: 'Generated by create-t3-app',
	icons: [{ rel: 'icon', url: '/trim.svg' }]
}

export default function RootLayout({
	children
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="es">
			<body
				className={cn(
					'dark px-4 sm:container max-w-xl grid gap-4 min-h-screen grid-rows-[auto,1fr,auto] bg-background antialiased font-sans',
					inter.variable
				)}
			>
				<main className="grid gap-12">{children}</main>
			</body>
		</html>
	)
}
